name: esig_utils
description: Utilitários para serem usados em projetos flutter.
version: 5.2.0
homepage: https://github.com/mobile_esig/esig_utils

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  extended_masked_text: ^2.1.0
  intl: ^0.17.0
  crypto: ^3.0.1

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
