name: release

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [main, develop]

    paths-ignore:
      - "**.md"
      - ".fvm/**"
      - ".github/**"
      - ".vscode/**"
      - "customizations/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  JAVA_VERSION: 11.x
  JAVA_DISTRIBUTION: temurin
  FLUTTER_VERSION: 3.3.10
  FLUTTER_CHANNEL: stable

jobs:
  build:
    name: Check PR
    runs-on: self-hosted-linux

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v3.1.0

      - name: Set up JDK  ⬇️
        uses: actions/setup-java@v3.5.1
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: SSH Agent ⬇️
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_KOBE_ECOMMERCE_CLOUD }}
            ${{ secrets.SSH_KOBE_ECOMMERCE_CORE }}
            ${{ secrets.SSH_KOBE_ECOMMERCE_DESIGN_SYSTEM }}
            ${{ secrets.SSH_KOBE_ECOMMERCE_PAYMENTS }}

      - name: Flutter Pub Get ⬇️
        run: fvm flutter pub get

      - name: Flutter Analyze ⬇️
        run: fvm flutter analyze > flutter_analyze_report.txt
        continue-on-error: true

      - name: Flutter Test ⬇️
        run: fvm flutter test --machine --coverage --update-goldens --tags=golden > test-results.json
        continue-on-error: true

      - name: Flutter Test Reporter ⬇️
        uses: dorny/test-reporter@v1
        with:
          name: test-results
          path: test-results.json
          reporter: flutter-json

      # begin Danger
      # - name: Setup Ruby ⬇️
      #   uses: actions/setup-ruby@v1
      #   with:
      #     ruby-version: ${{ env.RUBY_VERSION }}

      - name: Cache ⬇️
        uses: actions/cache@v3.0.11
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }} # change your gemfile path
          restore-keys: |
            ${{ runner.os }}-gems-

      # - name: Install Danger Flutter Lint ⬇️
      #   run: gem install danger-flutter_lint

      - run: bundle config set --local path 'vendor/bundle'

      - name: Danger Action ⬇️
        uses: MeilCli/danger-action@v5
        with:
          plugins_file: "Gemfile"
          install_path: "vendor/bundle"
          danger_file: "Dangerfile"
          danger_id: "danger-pr"
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.KOBINHO_DANGER_GITHUB_API_TOKEN }}
      # end Danger
